---
title: "Bad Boyle Data"
author: "rcj"
date: "23/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
```

## Purpose 

Testing Boyle's law.

## Method


We measured pressure using a guage and volume using something else.

### Aparatus

Balloons, bike-pump, guages.

## Observations

```{r}
good_boyle <- readr::read_csv(here::here("data/good_data.csv")) 

bad_boyle <- readr::read_csv(here::here("data/bad_data.csv")) %>% 
  mutate(
    pressure = pressure+ 
                  400*(runif(nrow(good_boyle))-0.5)
    )

boyle <- good_boyle
#boyle <- bad_boyle
```

We collected `r nrow(boyle)` records. The graph looks like this:

```{r}
boyle %>% ggplot2::ggplot()+
  ggplot2::geom_point(
    ggplot2::aes(x=volume, y=pressure)
    )+
  labs(title="Pressure, what pressure?")



```

Here is a table with our data:

```{r}
DT::datatable(boyle)
```


And we could generate the linear form:

```{r}
testdata <- boyle %>% mutate(oneoverV = 1/volume)
testdata %>% ggplot()+geom_point(aes(x=pressure, y=oneoverV))
```

## Conclusions

Here are some conclusions.

Here are

